# Procedimiento de ETL - PI 1

In [1]:
import pandas as pd

dfaws = pd.read_csv(r'./Data/amazon_prime_titles.csv', sep=',', encoding='UTF-8', thousands=',', decimal='.')
dfaws. head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [2]:
dfaws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [3]:
dfaws = dfaws.drop_duplicates()
dfaws.info()
# No posee valores duplicados, el dropna me bota mmuchos registros

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB



Propuesta de trabajo (requerimientos de aprobación)
Transformaciones: Para este MVP no necesitas perfección, ¡necesitas rapidez! ⏩ Vas a hacer estas, y solo estas, transformaciones a los datos:

Generar campo id: Cada id se compondrá de la primera letra del nombre de la plataforma, seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = as123)

In [4]:
dfaws['id'] = dfaws['show_id'].apply(lambda x: 'a' + str(x)) 
dfaws = dfaws.assign(plataforma='AWS') #discrimino la plataforma para luego poder diferenciar en el df maestro
dfaws = dfaws.drop('show_id', axis=1)
dfaws = dfaws[['id','plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']]
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,as1,AWS,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,as2,AWS,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,as3,AWS,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,as4,AWS,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,as5,AWS,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,AWS,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,as9665,AWS,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,as9666,AWS,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,as9667,AWS,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,as9668,AWS,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."


Los valores nulos del campo rating deberán reemplazarse por el string “G” (corresponde al maturity rating: “general for all audiences”

In [5]:
dfaws['rating'] = dfaws['rating'].fillna('G')
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,as1,AWS,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,as2,AWS,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,as3,AWS,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,as4,AWS,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,as5,AWS,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,AWS,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,as9665,AWS,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,as9666,AWS,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,as9667,AWS,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,as9668,AWS,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."


De haber fechas, deberán tener el formato AAAA-mm-dd

In [6]:

dfaws['date_added'] = pd.to_datetime(dfaws['date_added']) # transformo a formato date
dfaws['date_added'] = dfaws['date_added'].dt.strftime('%Y-%m-%d')  #cambio el formato de las fechas reordenando
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,as1,AWS,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,as2,AWS,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,as3,AWS,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,as4,AWS,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,as5,AWS,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,AWS,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,as9665,AWS,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,as9666,AWS,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,as9667,AWS,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,as9668,AWS,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."



Los campos de texto deberán estar en minúsculas, sin excepciones

In [7]:
dfaws = dfaws.applymap(lambda x: x.lower() if type(x) == str else x)
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,as1,aws,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...
1,as2,aws,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...
2,as3,aws,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...
3,as4,aws,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ..."
4,as5,aws,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,aws,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaN,1940,7+,60 min,comedy,new york city street principles get an east si...
9664,as9665,aws,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaN,2018,13+,4 seasons,tv shows,"this is earth, 2100ad - and these are the adve..."
9665,as9666,aws,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaN,2008,r,90 min,action,"in war-torn eastern europe, a world-weary grou..."
9666,as9667,aws,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaN,2021,tv-ma,1 season,"drama, sports","the series tells the story of diego maradona, ..."
9667,as9668,aws,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaN,2010,r,103 min,"action, drama, suspense","harry brown, starring two-time academy award w..."


El campo duration debe convertirse en dos campos: duration_int y duration_type. El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [8]:
dfaws[['duration_int', 'duration_type']] = dfaws['duration'].str.extract('(\d+) (\D+)')
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_int,duration_type
0,as1,aws,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,113,min
1,as2,aws,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,110,min
2,as3,aws,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,min
3,as4,aws,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",69,min
4,as5,aws,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,45,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,aws,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaN,1940,7+,60 min,comedy,new york city street principles get an east si...,60,min
9664,as9665,aws,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaN,2018,13+,4 seasons,tv shows,"this is earth, 2100ad - and these are the adve...",4,seasons
9665,as9666,aws,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaN,2008,r,90 min,action,"in war-torn eastern europe, a world-weary grou...",90,min
9666,as9667,aws,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaN,2021,tv-ma,1 season,"drama, sports","the series tells the story of diego maradona, ...",1,season
9667,as9668,aws,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaN,2010,r,103 min,"action, drama, suspense","harry brown, starring two-time academy award w...",103,min

In [9]:
dfaws.isnull().sum()

id                  0
plataforma          0
type                0
title               0
director         2083
cast             1233
country          8996
date_added       9513
release_year        0
rating              0
duration            0
listed_in           0
description         0
duration_int        0
duration_type       0
dtype: int64

In [10]:
# convierte la columna date_added a tipo datetime
dfaws['date_added'] = pd.to_datetime(dfaws['date_added'], errors='coerce')

# elige la fecha promedio y reemplaza los valores nulos en la columna date_added
date_mean = dfaws['date_added'].mean()
dfaws['date_added'].fillna(date_mean, inplace=True)

# selecciona sólo la fecha y conviértela en formato AAAA-mm-dd
dfaws['date_added'] = pd.Series(dfaws['date_added'].values).dt.strftime('%Y-%m-%d')

In [11]:
dfaws.isnull().sum()

id                  0
plataforma          0
type                0
title               0
director         2083
cast             1233
country          8996
date_added          0
release_year        0
rating              0
duration            0
listed_in           0
description         0
duration_int        0
duration_type       0
dtype: int64

In [12]:

dfaws.fillna('unknown', inplace=True)

In [13]:
dfaws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             9668 non-null   object
 1   plataforma     9668 non-null   object
 2   type           9668 non-null   object
 3   title          9668 non-null   object
 4   director       9668 non-null   object
 5   cast           9668 non-null   object
 6   country        9668 non-null   object
 7   date_added     9668 non-null   object
 8   release_year   9668 non-null   int64
 9   rating         9668 non-null   object
 10  duration       9668 non-null   object
 11  listed_in      9668 non-null   object
 12  description    9668 non-null   object
 13  duration_int   9668 non-null   object
 14  duration_type  9668 non-null   object
dtypes: int64(1), object(14)
memory usage: 1.1+ MB

In [14]:
#transformacion de todos los tipos de datos presentes en el df.
dfaws['id'] = dfaws['id'].astype('object')
dfaws['plataforma'] = dfaws['plataforma'].astype('category')
dfaws['type'] = dfaws['type'].astype('category')
dfaws['title'] = dfaws['title'].astype('object')
dfaws['director'] = dfaws['director'].astype('object')
dfaws['cast'] = dfaws['cast'].astype('object')
dfaws['country'] = dfaws['country'].astype('category')
dfaws['date_added'] = pd.to_datetime(dfaws['date_added'])
dfaws['release_year'] = dfaws['release_year'].astype('int64')
dfaws['rating'] = dfaws['rating'].astype('category')
dfaws['duration_int'] = dfaws['duration_int'].astype('int64')
dfaws['duration_type'] = dfaws['duration_type'].astype('category')
dfaws['listed_in'] = dfaws['listed_in'].astype('category')
dfaws['description'] = dfaws['description'].astype('object')

In [15]:
dfaws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             9668 non-null   object
 1   plataforma     9668 non-null   category
 2   type           9668 non-null   category
 3   title          9668 non-null   object
 4   director       9668 non-null   object
 5   cast           9668 non-null   object
 6   country        9668 non-null   category
 7   date_added     9668 non-null   datetime64[ns]
 8   release_year   9668 non-null   int64
 9   rating         9668 non-null   category
 10  duration       9668 non-null   object
 11  listed_in      9668 non-null   category
 12  description    9668 non-null   object
 13  duration_int   9668 non-null   int64
 14  duration_type  9668 non-null   category
dtypes: category(6), datetime64[ns](1), int64(2), object(6)
memory usage: 770.0+ KB

# En Resumen:

## AWS:

In [16]:
import pandas as pd

dfaws = pd.read_csv(r'./Data/amazon_prime_titles.csv', sep=',', encoding='UTF-8', thousands=',', decimal='.') # importo CSV.

dfaws = dfaws.drop_duplicates() #borro duplicates



dfaws['id'] = dfaws['show_id'].apply(lambda x: 'a' + str(x)) # agrego segun consigna la info a id column. Guardandola ahora como "id"
dfaws = dfaws.assign(plataforma='AWS') #discrimino la plataforma para luego poder diferenciar en el df maestro
dfaws = dfaws.drop('show_id', axis=1) # elimino vieja columna "show_id".
dfaws = dfaws[['id','plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']] # reordeno para mayor comodidad, reemplazando la nueva columna "id" en lugar de "show_id"


dfaws['rating'] = dfaws['rating'].fillna('G') #relleno nulos de rating seguun consigna con "G"




# De haber fechas, deberán tener el formato AAAA-mm-dd...
dfaws['date_added'] = pd.to_datetime(dfaws['date_added']) # transformo a formato date
dfaws['date_added'] = dfaws['date_added'].dt.strftime('%Y-%m-%d')  #cambio el formato de las fechas reordenando



dfaws = dfaws.applymap(lambda x: x.lower() if type(x) == str else x) #Transformo todo en minusculas por simplicidad y p/ evitar futuros errores.

dfaws[['duration_int', 'duration_type']] = dfaws['duration'].str.extract('(\d+) (\D+)') # Separo columna duration en duration_int (solo minutos) y duration type (seasons)
dfaws = dfaws.drop('duration', axis=1) # elimino vieja columna "duration" ya sustituida por las anteriores
dfaws = dfaws[['id','plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration_int','duration_type', 'listed_in', 'description']] # reordeno para mayor comodidad, reemplazando duration con duration_int y duration_type


# se observo en este dataframe valores faltantes en cast director country y date added (este ultimo será sustituido por el promedio del resto de las peliculas registradas en el csv, para minimizar la pérdida de datos)

# convierte la columna date_added a tipo datetime
dfaws['date_added'] = pd.to_datetime(dfaws['date_added'], errors='coerce')

# elige la fecha promedio y reemplaza los valores nulos en la columna date_added
date_mean = dfaws['date_added'].mean()
dfaws['date_added'].fillna(date_mean, inplace=True)

# selecciona sólo la fecha y conviértela en formato AAAA-mm-dd
dfaws['date_added'] = pd.Series(dfaws['date_added'].values).dt.strftime('%Y-%m-%d')


dfaws.fillna('unknown', inplace=True) # relleno los demas valores faltantes de country cast, director con "unknown" , tambien para minimizar la perdida de datos.

#transformacion de todos los tipos de datos presentes en el df.
dfaws['id'] = dfaws['id'].astype('object')
dfaws['plataforma'] = dfaws['plataforma'].astype('category')
dfaws['type'] = dfaws['type'].astype('category')
dfaws['title'] = dfaws['title'].astype('object')
dfaws['director'] = dfaws['director'].astype('object')
dfaws['cast'] = dfaws['cast'].astype('object')
dfaws['country'] = dfaws['country'].astype('category')
dfaws['date_added'] = pd.to_datetime(dfaws['date_added'])
dfaws['release_year'] = dfaws['release_year'].astype('int64')
dfaws['rating'] = dfaws['rating'].astype('category')
dfaws['duration_int'] = dfaws['duration_int'].astype('int64')
dfaws['duration_type'] = dfaws['duration_type'].astype('category')
dfaws['listed_in'] = dfaws['listed_in'].astype('category')
dfaws['description'] = dfaws['description'].astype('object')

In [17]:
# imprimo resultados:
dfaws

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration_int,duration_type,listed_in,description
0,as1,aws,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113,min,"comedy, drama",a small fishing village must procure a local d...
1,as2,aws,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110,min,"drama, international",a metro family decides to fight a cyber crimin...
2,as3,aws,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74,min,"action, drama, suspense",after a man discovers his wife is cheating on ...
3,as4,aws,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69,min,documentary,"pink breaks the mold once again, bringing her ..."
4,as5,aws,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45,min,"drama, fantasy",teenage matt banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,as9664,aws,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",unknown,2021-07-14,1940,7+,60,min,comedy,new york city street principles get an east si...
9664,as9665,aws,tv show,planet patrol,unknown,"dick vosburgh, ronnie stevens, libby morris, m...",unknown,2021-07-14,2018,13+,4,seasons,tv shows,"this is earth, 2100ad - and these are the adve..."
9665,as9666,aws,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",unknown,2021-07-14,2008,r,90,min,action,"in war-torn eastern europe, a world-weary grou..."
9666,as9667,aws,tv show,maradona: blessed dream,unknown,"esteban recagno, ezequiel stremiz, luciano vit...",unknown,2021-07-14,2021,tv-ma,1,season,"drama, sports","the series tells the story of diego maradona, ..."
9667,as9668,aws,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",unknown,2021-07-14,2010,r,103,min,"action, drama, suspense","harry brown, starring two-time academy award w..."

## Disney Plus:

In [18]:
import pandas as pd

dfdp = pd.read_csv(r'./Data/disney_plus_titles.csv', sep=',', encoding='UTF-8', thousands=',', decimal='.') # importo CSV.

dfdp = dfdp.drop_duplicates() #borro duplicates

dfdp['id'] = dfdp['show_id'].apply(lambda x: 'a' + str(x)) # agrego segun consigna la info a id column. Guardandola ahora como "id"
dfdp = dfdp.assign(plataforma='Disney Plus') #discrimino la plataforma para luego poder diferenciar en el df maestro
dfdp = dfdp.drop('show_id', axis=1) # elimino vieja columna "show_id".
dfdp = dfdp[['id','plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']] # reordeno para mayor comodidad, reemplazando la nueva columna "id" en lugar de "show_id"

dfdp['rating'] = dfdp['rating'].fillna('G') #relleno nulos de rating seguun consigna con "G"

# De haber fechas, deberán tener el formato AAAA-mm-dd...
dfdp['date_added'] = pd.to_datetime(dfdp['date_added']) # transformo a formato date
dfdp['date_added'] = dfdp['date_added'].dt.strftime('%Y-%m-%d')  #cambio el formato de las fechas reordenando

dfdp = dfdp.applymap(lambda x: x.lower() if type(x) == str else x) #Transformo todo en minusculas por simplicidad y p/ evitar futuros errores.

dfdp[['duration_int', 'duration_type']] = dfdp['duration'].str.extract('(\d+) (\D+)') # Separo columna duration en duration_int (solo minutos) y duration type (seasons)
dfdp = dfdp.drop('duration', axis=1) # elimino vieja columna "duration" ya sustituida por las anteriores
dfdp = dfdp[['id','plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration_int','duration_type', 'listed_in', 'description']] # reordeno para mayor comodidad, reemplazando duration con duration_int y duration_type

# se observo en este dataframe valores faltantes en cast director country y date added (este ultimo será sustituido por el promedio del resto de las peliculas registradas en el csv, para minimizar la pérdida de datos)

# convierte la columna date_added a tipo datetime
dfdp['date_added'] = pd.to_datetime(dfdp['date_added'], errors='coerce')

# elige la fecha promedio y reemplaza los valores nulos en la columna date_added
date_mean = dfdp['date_added'].mean()
dfdp['date_added'].fillna(date_mean, inplace=True)

# selecciona sólo la fecha y conviértela en formato AAAA-mm-dd
dfdp['date_added'] = pd.Series(dfdp['date_added'].values).dt.strftime('%Y-%m-%d')

dfdp.fillna('unknown', inplace=True) # relleno los demas valores faltantes de country cast, director con "unknown" , tambien para minimizar la perdida de datos.

#transformacion de todos los tipos de datos presentes en el df.
dfdp['id'] = dfdp['id'].astype('object')
dfdp['plataforma'] = dfdp['plataforma'].astype('category')
dfdp['type'] = dfdp['type'].astype('category')
dfdp['title'] = dfdp['title'].astype('object')
dfdp['director'] = dfdp['director'].astype('object')
dfdp['cast'] = dfdp['cast'].astype('object')
dfdp['country'] = dfdp['country'].astype('category')
dfdp['date_added'] = pd.to_datetime(dfdp['date_added'])
dfdp['release_year'] = dfdp['release_year'].astype('int64')
dfdp['rating'] = dfdp['rating'].astype('category')
dfdp['duration_int'] = dfdp['duration_int'].astype('int64')
dfdp['duration_type'] = dfdp['duration_type'].astype('category')
dfdp['listed_in'] = dfdp['listed_in'].astype('category')
dfdp['description'] = dfdp['description'].astype('object')

In [19]:
dfdp

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration_int,duration_type,listed_in,description
0,as1,disney plus,movie,duck the halls: a mickey mouse christmas special,"alonso ramirez ramos, dave wasson","chris diamantopoulos, tony anselmo, tress macn...",unknown,2021-11-26,2016,tv-g,23,min,"animation, family",join mickey and the gang as they duck the halls!
1,as2,disney plus,movie,ernest saves christmas,john cherry,"jim varney, noelle parker, douglas seale",unknown,2021-11-26,1988,pg,91,min,comedy,santa claus passes his magic bag to a new st. ...
2,as3,disney plus,movie,ice age: a mammoth christmas,karen disher,"raymond albert romano, john leguizamo, denis l...",united states,2021-11-26,2011,tv-g,23,min,"animation, comedy, family",sid the sloth is on santa's naughty list.
3,as4,disney plus,movie,the queen family singalong,hamish hamilton,"darren criss, adam lambert, derek hough, alexa...",unknown,2021-11-26,2021,tv-pg,41,min,musical,"this is real life, not just fantasy!"
4,as5,disney plus,tv show,the beatles: get back,unknown,"john lennon, paul mccartney, george harrison, ...",unknown,2021-11-25,2021,g,1,season,"docuseries, historical, music",a three-part documentary from peter jackson ca...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,as1446,disney plus,movie,x-men origins: wolverine,gavin hood,"hugh jackman, liev schreiber, danny huston, wi...","united states, united kingdom",2021-06-04,2009,pg-13,108,min,"action-adventure, family, science fiction",wolverine unites with legendary x-men to fight...
1446,as1447,disney plus,movie,night at the museum: battle of the smithsonian,shawn levy,"ben stiller, amy adams, owen wilson, hank azar...","united states, canada",2021-04-02,2009,pg,106,min,"action-adventure, comedy, family",larry daley returns to rescue some old friends...
1447,as1448,disney plus,movie,eddie the eagle,dexter fletcher,"tom costello, jo hartley, keith allen, dickon ...","united kingdom, germany, united states",2020-12-18,2016,pg-13,107,min,"biographical, comedy, drama","true story of eddie edwards, a british ski-jum..."
1448,as1449,disney plus,movie,bend it like beckham,gurinder chadha,"parminder nagra, keira knightley, jonathan rhy...","united kingdom, germany, united states",2020-09-18,2003,pg-13,112,min,"buddy, comedy, coming of age",despite the wishes of their traditional famili...
1449,as1450,disney plus,movie,captain sparky vs. the flying saucers,mark waring,charlie tahan,united states,2020-04-01,2012,tv-g,2,min,"action-adventure, animals & nature, animation",view one of sparky's favorite home movies.

## Hulu:

In [20]:
import pandas as pd # en ingles, solo para practicar.. XD

df_hulu = pd.read_csv(r'./Data/hulu_titles.csv', sep=',', encoding='UTF-8', thousands=',', decimal='.') # import CSV.

df_hulu = df_hulu.drop_duplicates() # drop duplicates

df_hulu['id'] = df_hulu['show_id'].apply(lambda x: 'b' + str(x)) # add info to id column as instructed, now saved as "id"
df_hulu = df_hulu.assign(plataforma='Hulu') # discriminate platform to later differentiate in the master df
df_hulu = df_hulu.drop('show_id', axis=1) # remove old "show_id" column
df_hulu = df_hulu[['id', 'plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']] # reorder for convenience, replacing the new "id" column instead of "show_id"

df_hulu['rating'] = df_hulu['rating'].fillna('G') # fill in missing ratings as instructed with "G"

# If there are dates, they should have the format YYYY-mm-dd...
df_hulu['date_added'] = pd.to_datetime(df_hulu['date_added']) # convert to date format
df_hulu['date_added'] = df_hulu['date_added'].dt.strftime('%Y-%m-%d') # rearrange date format

df_hulu = df_hulu.applymap(lambda x: x.lower() if type(x) == str else x) # convert everything to lowercase for simplicity and to avoid future errors.

df_hulu[['duration_int', 'duration_type']] = df_hulu['duration'].str.extract('(\d+) (\D+)') # Separate duration column into duration_int (only minutes) and duration type (seasons)
df_hulu = df_hulu.drop('duration', axis=1) # remove old "duration" column already replaced by the previous ones
df_hulu = df_hulu[['id', 'plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration_int', 'duration_type', 'listed_in', 'description']] # reorder for convenience, replacing duration with duration_int and duration_type
df_hulu.isnull().sum()


# Missing values were observed in cast, director, country, and some more..  and date added columns (the latter will be replaced by the average of the rest of the movies recorded in the CSV to minimize data loss)

# Convert the date_added column to datetime type
df_hulu['date_added'] = pd.to_datetime(df_hulu['date_added'], errors='coerce')

# Choose the mean date and replace the null values in the date_added column
date_mean = df_hulu['date_added'].mean()
df_hulu['date_added'].fillna(date_mean, inplace=True)

# Select only the date and convert it to YYYY-mm-dd format
df_hulu['date_added'] = pd.Series(df_hulu['date_added'].values).dt.strftime('%Y-%m-%d')


# Choose the mean duration_int and replace the null values in the duration_int column
df_hulu['duration_int'] = df_hulu['duration_int'].astype(float)
duration_int_mean = df_hulu['duration_int'].mean()
df_hulu['duration_int'].fillna(duration_int_mean, inplace=True)



#completo el resto de faltantes con unknown
df_hulu.fillna('unknown', inplace=True) # fill in remaining missing values in country, cast, director with "unknown" to minimize data loss.

# transformación de todos los tipos de datos presentes en el df
df_hulu['id'] = df_hulu['id'].astype('object')
df_hulu['plataforma'] = df_hulu['plataforma'].astype('category')
df_hulu['type'] = df_hulu['type'].astype('category')
df_hulu['title'] = df_hulu['title'].astype('object')
df_hulu['director'] = df_hulu['director'].astype('object')
df_hulu['cast'] = df_hulu['cast'].astype('object')
df_hulu['country'] = df_hulu['country'].astype('category')
df_hulu['date_added'] = pd.to_datetime(df_hulu['date_added'])
df_hulu['release_year'] = df_hulu['release_year'].astype('int64')
df_hulu['rating'] = df_hulu['rating'].astype('category')
df_hulu['duration_int'] = df_hulu['duration_int'].astype('int64')
df_hulu['duration_type'] = df_hulu['duration_type'].astype('category')
df_hulu['listed_in'] = df_hulu['listed_in'].astype('category')
df_hulu['description'] = df_hulu['description'].astype('object')

In [21]:
df_hulu

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration_int,duration_type,listed_in,description
0,bs1,hulu,movie,ricky velez: here's everything,unknown,unknown,unknown,2021-10-24,2021,tv-ma,39,unknown,"comedy, stand up",​comedian ricky velez bares it all with his ho...
1,bs2,hulu,movie,silent night,unknown,unknown,unknown,2021-10-23,2020,g,94,min,"crime, drama, thriller","mark, a low end south london hitman recently r..."
2,bs3,hulu,movie,the marksman,unknown,unknown,unknown,2021-10-23,2021,pg-13,108,min,"action, thriller",a hardened arizona rancher tries to protect an...
3,bs4,hulu,movie,gaia,unknown,unknown,unknown,2021-10-22,2021,r,97,min,horror,a forest ranger and two survivalists with a cu...
4,bs5,hulu,movie,settlers,unknown,unknown,unknown,2021-10-22,2021,g,104,min,"science fiction, thriller",mankind's earliest settlers on the martian fro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,bs3069,hulu,tv show,star trek: the original series,unknown,unknown,united states,2019-10-31,1966,tv-pg,3,seasons,"action, adventure, classics",the 23rd century adventures of captain james t...
3069,bs3070,hulu,tv show,star trek: voyager,unknown,unknown,united states,2019-10-31,1997,tv-pg,7,seasons,"action, adventure, science fiction",catapulted into the distant sector of the gala...
3070,bs3071,hulu,tv show,the fades,unknown,unknown,united kingdom,2019-10-31,2011,tv-14,1,season,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...
3071,bs3072,hulu,tv show,the twilight zone,unknown,unknown,united states,2019-10-31,1959,tv-pg,5,seasons,"classics, science fiction, thriller",rod serling's seminal anthology series focused...
3072,bs3073,hulu,tv show,tokyo magnitude 8.0,unknown,unknown,japan,2019-10-31,2009,tv-14,1,season,"anime, drama, international",the devastation is unleashed in the span of se...

## Netflix:

In [22]:
import pandas as pd

df_netflix = pd.read_csv(r'./Data/netflix_titles.csv', sep=',', encoding='UTF-8', thousands=',', decimal='.')
df_netflix = df_netflix.drop_duplicates()

df_netflix['id'] = df_netflix['show_id'].apply(lambda x: 'b' + str(x))
df_netflix = df_netflix.assign(plataforma='Netflix')
df_netflix = df_netflix.drop('show_id', axis=1)
df_netflix = df_netflix[['id', 'plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']]

df_netflix['rating'] = df_netflix['rating'].fillna('G')

df_netflix['date_added'] = pd.to_datetime(df_netflix['date_added'], errors='coerce')
date_mean = df_netflix['date_added'].mean()
df_netflix['date_added'].fillna(date_mean, inplace=True)
df_netflix['date_added'] = df_netflix['date_added'].dt.strftime('%Y-%m-%d')

df_netflix = df_netflix.applymap(lambda x: x.lower() if type(x) == str else x)
df_netflix[['duration_int', 'duration_type']] = df_netflix['duration'].str.extract('(\d+) (\D+)')
df_netflix = df_netflix.drop('duration', axis=1)
f_netflix = df_netflix[['id', 'plataforma', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration_int', 'duration_type', 'listed_in', 'description']]
df_netflix.isnull().sum()

# Convert duration_int column to float
df_netflix['duration_int'] = df_netflix['duration_int'].astype(float)

# Fill missing values with mean duration_int
duration_int_mean = df_netflix['duration_int'].mean()
df_netflix['duration_int'].fillna(duration_int_mean, inplace=True)

df_netflix.fillna('unknown', inplace=True)
df_netflix['id'] = df_netflix['id'].astype('object')
df_netflix['plataforma'] = df_netflix['plataforma'].astype('category')
df_netflix['type'] = df_netflix['type'].astype('category')
df_netflix['title'] = df_netflix['title'].astype('object')
df_netflix['director'] = df_netflix['director'].astype('object')
df_netflix['cast'] = df_netflix['cast'].astype('object')
df_netflix['country'] = df_netflix['country'].astype('category')
df_netflix['date_added'] = pd.to_datetime(df_netflix['date_added'], errors='coerce')
df_netflix['date_added'].fillna(date_mean, inplace=True)
df_netflix['date_added'] = df_netflix['date_added'].dt.strftime('%Y-%m-%d')

df_netflix['release_year'] = df_netflix['release_year'].astype('int64')
df_netflix['rating'] = df_netflix['rating'].astype('category')
df_netflix['duration_int'] = df_netflix['duration_int'].astype('int64')
df_netflix['duration_type'] = df_netflix['duration_type'].astype('category')
df_netflix['listed_in'] = df_netflix['listed_in'].astype('category')
df_netflix['description'] = df_netflix['description'].astype('object')

In [23]:
df_netflix.head()

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,duration_int,duration_type
0,bs1,netflix,movie,dick johnson is dead,kirsten johnson,unknown,united states,2021-09-25,2020,pg-13,documentaries,"as her father nears the end of his life, filmm...",90,min
1,bs2,netflix,tv show,blood & water,unknown,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",2,seasons
2,bs3,netflix,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",unknown,2021-09-24,2021,tv-ma,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,1,season
3,bs4,netflix,tv show,jailbirds new orleans,unknown,unknown,unknown,2021-09-24,2021,tv-ma,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",1,season
4,bs5,netflix,tv show,kota factory,unknown,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,2,seasons

# CONCATENANDO LOS DATAFRAME:

In [24]:
#concat
df = pd.concat([dfaws, dfdp, df_netflix, df_hulu], ignore_index=True)

In [25]:
df['id'] = df['id'].astype('object')
df['plataforma'] = df['plataforma'].astype('category')
df['type'] = df['type'].astype('category')
df['title'] = df['title'].astype('object')
df['director'] = df['director'].astype('object')
df['cast'] = df['cast'].astype('object')
df['country'] = df['country'].astype('category')
df['date_added'] = pd.to_datetime(df['date_added'])
df['release_year'] = df['release_year'].astype('int64')
df['rating'] = df['rating'].astype('category')
df['duration_int'] = df['duration_int'].astype('int64')
df['duration_type'] = df['duration_type'].astype('category')
df['listed_in'] = df['listed_in'].astype('category')
df['description'] = df['description'].astype('object')

In [26]:
df.head(10)

,id,plataforma,type,title,director,cast,country,date_added,release_year,rating,duration_int,duration_type,listed_in,description
0,as1,aws,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113,min,"comedy, drama",a small fishing village must procure a local d...
1,as2,aws,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110,min,"drama, international",a metro family decides to fight a cyber crimin...
2,as3,aws,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74,min,"action, drama, suspense",after a man discovers his wife is cheating on ...
3,as4,aws,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69,min,documentary,"pink breaks the mold once again, bringing her ..."
4,as5,aws,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45,min,"drama, fantasy",teenage matt banting wants to work with a famo...
5,as6,aws,movie,living with dinosaurs,paul weiland,"gregory chisholm, juliet stevenson, brian hens...",united kingdom,2021-03-30,1989,g,52,min,"fantasy, kids",the story unfolds in a an english seaside town...
6,as7,aws,movie,hired gun,fran strine,"alice cooper, liberty devitto, ray parker jr.,...",united states,2021-03-30,2017,g,98,min,"documentary, special interest","they are the ""first call, a-list"" musicians, j..."
7,as8,aws,movie,grease live!,"thomas kail, alex rudzinski","julianne hough, aaron tveit, vanessa hudgens, ...",united states,2021-03-30,2016,g,131,min,comedy,"this honest, uncompromising comedy chronicles ..."
8,as9,aws,movie,global meltdown,daniel gilboy,"michael paré, leanne khol young, patrick j. ma...",canada,2021-03-30,2017,g,87,min,"action, science fiction, suspense",a helicopter pilot and an environmental scient...
9,as10,aws,movie,david's mother,robert allan ackerman,"kirstie alley, sam waterston, stockard channing",united states,2021-04-01,1994,g,92,min,drama,sally goodson is a devoted mother to her autis...

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             22998 non-null  object
 1   plataforma     22998 non-null  category
 2   type           22998 non-null  category
 3   title          22998 non-null  object
 4   director       22998 non-null  object
 5   cast           22998 non-null  object
 6   country        22998 non-null  category
 7   date_added     22998 non-null  datetime64[ns]
 8   release_year   22998 non-null  int64
 9   rating         22998 non-null  category
 10  duration_int   22998 non-null  int64
 11  duration_type  22998 non-null  category
 12  listed_in      22998 non-null  category
 13  description    22998 non-null  object
dtypes: category(6), datetime64[ns](1), int64(2), object(5)
memory usage: 1.7+ MB

In [28]:
print(pd.__version__)


# Convert columns to desired data types
df['id'] = df['id'].astype(str)
df['plataforma'] = df['plataforma'].astype('category')
df['type'] = df['type'].astype('category')
df['title'] = df['title'].astype(str)
df['director'] = df['director'].astype(str)
df['cast'] = df['cast'].astype(str)
df['country'] = df['country'].astype('category')
df['date_added'] = pd.to_datetime(df['date_added'])
df['release_year'] = df['release_year'].astype(int)
df['rating'] = df['rating'].astype('category')
df['duration_int'] = df['duration_int'].astype(int)
df['duration_type'] = df['duration_type'].astype('category')
df['listed_in'] = df['listed_in'].astype('category')
df['description'] = df['description'].astype(str)

2.0.0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             22998 non-null  object
 1   plataforma     22998 non-null  category
 2   type           22998 non-null  category
 3   title          22998 non-null  object
 4   director       22998 non-null  object
 5   cast           22998 non-null  object
 6   country        22998 non-null  category
 7   date_added     22998 non-null  datetime64[ns]
 8   release_year   22998 non-null  int32
 9   rating         22998 non-null  category
 10  duration_int   22998 non-null  int32
 11  duration_type  22998 non-null  category
 12  listed_in      22998 non-null  category
 13  description    22998 non-null  object
dtypes: category(6), datetime64[ns](1), int32(2), object(5)
memory usage: 1.5+ MB

In [30]:
# Guardar el dataframe como un archivo CSV
df.to_csv("./Data/Base_de_datos_aws_dp_hulu_netflix.csv", mode='a', header=True, index=False )

_________________________________________________________________________________________________________________________________________________________